// File generated by FlutterFire CLI & customized for Singular cross-platform desktop & mobile support.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] used by [Firebase.initializeApp].
class DefaultFirebaseOptions {
  static const String _defaultApiKey = String.fromEnvironment(
    'FIREBASE_API_KEY',
    defaultValue: 'AIzaSyPlaceholderApiKeyForSingularApp',
  );
  static const String _defaultAppId = String.fromEnvironment(
    'FIREBASE_APP_ID',
    defaultValue: '1:100000000000:web:abcdef1234567890',
  );
  static const String _defaultMessagingSenderId = String.fromEnvironment(
    'FIREBASE_MESSAGING_SENDER_ID',
    defaultValue: '100000000000',
  );
  static const String _defaultProjectId = String.fromEnvironment(
    'FIREBASE_PROJECT_ID',
    defaultValue: 'singular-app',
  );
  static const String _defaultMeasurementId = String.fromEnvironment(
    'FIREBASE_MEASUREMENT_ID',
    defaultValue: 'G-XXXXXXXXXX',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        return windows;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _defaultApiKey,
    appId: _defaultAppId,
    messagingSenderId: _defaultMessagingSenderId,
    projectId: _defaultProjectId,
    measurementId: _defaultMeasurementId,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _defaultApiKey,
    appId: _defaultAppId,
    messagingSenderId: _defaultMessagingSenderId,
    projectId: _defaultProjectId,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _defaultApiKey,
    appId: _defaultAppId,
    messagingSenderId: _defaultMessagingSenderId,
    projectId: _defaultProjectId,
    iosBundleId: 'com.example.singular',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _defaultApiKey,
    appId: _defaultAppId,
    messagingSenderId: _defaultMessagingSenderId,
    projectId: _defaultProjectId,
    iosBundleId: 'com.example.singular',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _defaultApiKey,
    appId: _defaultAppId,
    messagingSenderId: _defaultMessagingSenderId,
    projectId: _defaultProjectId,
    measurementId: _defaultMeasurementId,
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: _defaultApiKey,
    appId: _defaultAppId,
    messagingSenderId: _defaultMessagingSenderId,
    projectId: _defaultProjectId,
    measurementId: _defaultMeasurementId,
  );
}
